name: bornomala
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  getwidget: ^4.0.0
  flutter_screenutil: ^5.9.3
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  avatar_glow: ^3.0.1
  flutter_gradient_text: ^1.0.1
  bordered_text: ^2.0.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/logos/
    - assets/alphabets/
